name 'core-linux'
maintainer 'Steven Wade'
maintainer_email 'wades@parliament.uk'
license 'all_rights'
description 'Installs/Configures template'
long_description 'Installs/Configures template'
version '0.1.0'
depends 'chef-client'
